{% set name = "napari-bioformats" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 16a75cdd6121212153052462098de6501eded880c78773b68e361a1260c4552a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - napari-plugin-engine >=0.1.4
    - numpy
    - pims
    - jpype1
    - ome-types

test:
  imports:
    - napari_bioformats
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/napari-bioformats
  summary: Bioformats for napari, using pims
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/tlambert03/napari-bioformats

extra:
  recipe-maintainers:
    - tlambert03
